{
 "title": "Sensor Status Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "FactoryID", "query": "1,2,3,4,5" }
  ]
 },
 "panels": [
  {
   "title": "Total Sensors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as Total_Sensors\nFROM\n  status"
    }
   ]
  },
  {
   "title": "Total Failed Sensors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) as Failed_Sensors\nFROM\n  status\nWHERE\n  status = 'FAILED'\n"
    }
   ]
  },
  {
   "title": "Failed Sensor Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*), sensor_type from status where status = 'FAILED'\ngroup by sensor_type\n"
    }
   ]
  },
  {
   "title": "Failure Per Section - Factory $FactoryID",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    section ,\n  count(status)\nFROM status\nWHERE\n  status = 'FAILED' and factory_id = $FactoryID\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Failed and Active Sensor ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select cast(coalesce(A.factory_id, F.factory_id) as text)  factory_id  ,F.Failed_Sensors,\r\nA.Active_Sensors\r\nFROM\r\n(SELECT\r\n  factory_id,count(*) as Failed_Sensors\r\nFROM   status WHERE status = 'FAILED'group by factory_id) F\r\nFULL OUTER JOIN\r\n(SELECT\r\n  factory_id,count(*) as Active_Sensors\r\nFROM   status WHERE status = 'ACTIVE'group by factory_id) A\r\nON F.factory_id = A.factory_id\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Failed Sensors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select factory_id as Factory,device_id as Device, section, sensor_type as Type,  eventtime as \"Last Event\" from status where status = 'FAILED'\norder by 1\n"
    }
   ]
  }
 ]
}